#! /bin/sh

# sxhkd
killall -s SIGKILL sxhkd
sxhkd &

## Enable clipboard manager
clipmenud &

# Enable redshift
killall -s SIGKILL redshift
redshift -x
redshift &

# Polybar
$HOME/.config/polybar/launch.sh

# Picom
picom --config ~/.picom.conf &

source ~/.xprofile

bspc monitor -d I II III IV V VI VII VIII IX X

# Background
# nitrogen --set-centered /usr/share/backgrounds/archlinux/archlinux-simplyblack.png &
nitrogen --set-scaled /usr/share/backgrounds/archlinux/landscape.jpg &

bspc config border_width         1
bspc config window_gap          10

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
# bspc config normal_border_color  \#FFFFFF
# bspc config active_border_color  \#FFFFFF
bspc config presel_feedback_color \#404040

bspc rule -a TelegramDesktop desktop='^9' follow=on
bspc rule -a Gimp desktop='^10' follow=on
bspc rule -a firefox desktop='^3' follow=on
bspc rule -a Chromium desktop='^6' follow=on
bspc rule -a Screenkey manage=off
# bspc rule -a jetbrains-idea desktop='^4' follow=on
# bspc rule -a Gimp desktop='^8' state=floating follow=on
